import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerHasWallet } from "./has-wallet.js";
import { registerHasProviders } from "./has-providers.js";
import { registerSetupWallet } from "./setup-wallet.js";
import { registerGetBalance } from "./get-balance.js";
import { registerGetAllBalances } from "./get-all-balances.js";
import { registerGetSwapQuote } from "./get-swap-quote.js";
import { registerExecuteSwap } from "./execute-swap.js";
import { registerTransfer } from "./transfer.js";
import { registerWrap, registerUnwrap } from "./wrap.js";
import { registerStake } from "./stake.js";
import { registerCheckSessionKeyBalance } from "./check-session-key-balance.js";
import { registerFundSessionKey } from "./fund-session-key.js";
import { registerListVerifiedTokens } from "./list-verified-tokens.js";
import { registerSetMode } from "./set-mode.js";
import { registerGetAccountInfo } from "./get-account-info.js";
import { registerGetTokenInfo } from "./get-token-info.js";
import { registerWithdrawSessionKey } from "./withdraw-session-key.js";
import { registerGetBlock } from "./get-block.js";
import { registerGetGasPrice } from "./get-gas-price.js";
import { registerExplainTransaction } from "./explain-transaction.js";
import { registerGetOnchainActivity } from "./get-onchain-activity.js";
import { registerExplainContract } from "./explain-contract.js";
import { registerNadFunStatus } from "./nadfun-status.js";
import { registerNadFunQuote } from "./nadfun-quote.js";
import { registerNadFunBuy } from "./nadfun-buy.js";
import { registerNadFunSell } from "./nadfun-sell.js";
import { registerNadFunDiscover } from "./nadfun-discover.js";
import { registerNadFunTokenInfo } from "./nadfun-token-info.js";
import { registerNadFunPositions } from "./nadfun-positions.js";
import { registerNadFunCreate } from "./nadfun-create.js";
import { registerLeverUpListPairs } from "./leverup-list-pairs.js";
import { registerLeverUpListPositions } from "./leverup-list-positions.js";
import { registerLeverUpGetQuote } from "./leverup-get-quote.js";
import { registerLeverUpOpenTrade } from "./leverup-open-trade.js";
import { registerLeverUpCloseTrade } from "./leverup-close-trade.js";
import { registerLeverUpUpdateMargin } from "./leverup-update-margin.js";
import { registerLeverUpUpdateTpSl } from "./leverup-update-tpsl.js";
import { registerLeverUpGetMarketStats } from "./leverup-get-market-stats.js";
import { registerLeverUpOpenLimitOrder } from "./leverup-open-limit-order.js";
import { registerLeverUpListLimitOrders } from "./leverup-list-limit-orders.js";
import { registerLeverUpCancelLimitOrder } from "./leverup-cancel-limit-order.js";
import { registerMarketGetChart } from "./market-get-chart.js";

export function registerTools(server: McpServer): void {
  registerHasWallet(server);
  registerHasProviders(server);
  registerSetupWallet(server);
  registerSetMode(server);
  registerGetBalance(server);
  registerGetAllBalances(server);
  registerListVerifiedTokens(server);
  registerGetTokenInfo(server);
  registerGetAccountInfo(server);
  registerCheckSessionKeyBalance(server);
  registerFundSessionKey(server);
  registerWithdrawSessionKey(server);
  registerGetSwapQuote(server);
  registerExecuteSwap(server);
  registerTransfer(server);
  registerWrap(server);
  registerUnwrap(server);
  registerStake(server);
  registerGetBlock(server);
  registerGetGasPrice(server);
  registerExplainTransaction(server);
  registerGetOnchainActivity(server);
  registerExplainContract(server);
  registerNadFunStatus(server);
  registerNadFunQuote(server);
  registerNadFunBuy(server);
  registerNadFunSell(server);
  registerNadFunDiscover(server);
  registerNadFunTokenInfo(server);
  registerNadFunPositions(server);
  registerNadFunCreate(server);
  registerLeverUpListPairs(server);
  registerLeverUpListPositions(server);
  registerLeverUpGetQuote(server);
  registerLeverUpOpenTrade(server);
  registerLeverUpCloseTrade(server);
  registerLeverUpUpdateMargin(server);
  registerLeverUpUpdateTpSl(server);
  registerLeverUpGetMarketStats(server);
  registerLeverUpOpenLimitOrder(server);
  registerLeverUpListLimitOrders(server);
  registerLeverUpCancelLimitOrder(server);
  registerMarketGetChart(server);
}
